# Generated by Django 2.2.13 on 2021-02-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_categories', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
