# Generated by Django 2.2.13 on 2021-04-15 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('developer_type', models.CharField(max_length=200)),
                ('most_prefered_language', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(upload_to='profileImage/')),
                ('about', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
