# Generated by Django 2.2.13 on 2021-04-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_allprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprofile',
            name='backendframework',
            field=models.CharField(choices=[('Django', 'Django'), ('Laravel', 'Larvel'), ('Ruby on Rails', 'Ruby on Rails'), ('NodeJS', 'NodeJS'), ('CakePHP', 'CakePHP'), ('Flask', 'Flask'), ('Asp.NET', 'Asp.NET'), ('Spring Boot', 'Spring Boot'), ('Koa', 'Koa'), ('Phoenix', 'Phoenix')], default='Not working', max_length=50),
        ),
        migrations.AddField(
            model_name='allprofile',
            name='frontendframework',
            field=models.CharField(choices=[('React', 'React'), ('Angular', 'Angular'), ('Vue.js', 'Vue.js'), ('AngularJS', 'AngularJS'), ('Svelte', 'Svelte'), ('Express.js', 'Express.js'), ('Next.js', 'Next.js')], default='Not working', max_length=50),
        ),
        migrations.AddField(
            model_name='allprofile',
            name='languages',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Javascript', 'Javascript'), ('Ruby', 'Ruby'), ('C', 'C'), ('C++', 'C++'), ('GO', 'GO'), ('R', 'R'), ('Perl', 'Perl'), ('Swift', 'Swift'), ('PHP', 'PHP'), ('Objective-C', 'Objective-C'), ('C#', 'C#'), ('SQL', 'SQL')], default='Not working', max_length=50),
        ),
    ]
