# Generated by Django 2.2.13 on 2021-04-18 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developer', '0004_auto_20210416_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprofile',
            name='Git_Hub_Url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='allprofile',
            name='LinkedIn_Url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='allprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='allprofile',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='allprofile',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='allprofile',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='allprofile',
            name='website_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='allprofile',
            name='backendframework',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='allprofile',
            name='developer_type',
            field=models.CharField(choices=[('Full Stack Developer', 'Full Stack Developer'), ('Front-End Developer', 'Front-End Developer'), ('Back-End Developer', 'Back-End Developer')], default='Full Stack Developer', max_length=50),
        ),
        migrations.AlterField(
            model_name='allprofile',
            name='frontendframework',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='allprofile',
            name='languages',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
