# Generated by Django 2.2.13 on 2021-04-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_auto_20210418_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='allprofile',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
