# Generated by Django 2.2.13 on 2021-04-21 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_auto_20210418_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='message',
        ),
        migrations.AddField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.AllProfile'),
        ),
    ]
