# Generated by Django 2.2.13 on 2021-04-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_auto_20210421_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='user',
            new_name='invitee',
        ),
    ]
