# Generated by Django 2.2.3 on 2021-05-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0008_auto_20210421_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=225)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.AllProfile')),
            ],
        ),
    ]
