# Generated by Django 2.2.3 on 2021-05-10 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0010_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='accepter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.AllProfile'),
        ),
        migrations.AlterField(
            model_name='response',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
