# Generated by Django 2.2.13 on 2021-05-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0011_auto_20210510_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
