# Generated by Django 2.2.13 on 2021-05-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0013_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprofile',
            name='backendframework',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='allprofile',
            name='frontendframework',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='allprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
