# Generated by Django 2.2.13 on 2021-05-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0014_auto_20210511_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allprofile',
            old_name='backendframework',
            new_name='angular',
        ),
        migrations.RenameField(
            model_name='allprofile',
            old_name='frontendframework',
            new_name='bootstrap',
        ),
        migrations.RenameField(
            model_name='allprofile',
            old_name='languages',
            new_name='css',
        ),
        migrations.RemoveField(
            model_name='allprofile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='allprofile',
            name='developer_type',
        ),
        migrations.RemoveField(
            model_name='allprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='allprofile',
            name='most_prefered_language',
        ),
        migrations.AddField(
            model_name='allprofile',
            name='django',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='allprofile',
            name='flask',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='allprofile',
            name='javascript',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='allprofile',
            name='nodejs',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='allprofile',
            name='php',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='allprofile',
            name='react',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='allprofile',
            name='vuejs',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='allprofile',
            name='email',
            field=models.CharField(max_length=225),
        ),
    ]
